version: '2'
services:
  data: 
    build: ./data
    volumes:
      - ../:/data
      - /var/lib/mysql
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes_from:
      - data
  php:
    build: ./php
    ports:
      - '8081:80'
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql
  composer:
    build: ./composer
    volumes_from:
      - data
